//
//  TextAbout.swift
//  modulotech.test
//
//  Created by hassine othmane on 1/16/19.
//  Copyright © 2019 modulotech.fr. All rights reserved.
//

import Foundation


let textAbout = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec blandit lobortis felis, quis porttitor magna lacinia non. Proin at hendrerit arcu. Aenean vitae convallis dui. Nunc porttitor lacus volutpat tellus sollicitudin, non sodales magna tincidunt. Pellentesque est ipsum, volutpat sit amet faucibus eget, dignissim vel libero. Nam a arcu auctor, accumsan magna ac, vulputate dui. Quisque tristique, tellus tristique euismod consequat, tortor nibh hendrerit nisi, a facilisis erat lacus et ipsum. Aenean accumsan risus velit, nec placerat magna ullamcorper sed. Ut nunc ante, dignissim vitae tortor ultrices, aliquam faucibus diam. Nulla ipsum dui, accumsan vel sodales quis, lacinia sit amet sapien. Nam cursus quam sit amet congue rutrum. Suspendisse turpis nulla, porttitor sed placerat et, vehicula posuere ligula. Nulla eu placerat lectus, nec lobortis eros. Etiam sit amet faucibus nulla.\n\nAenean posuere ex pretium purus tristique venenatis. Fusce semper rutrum aliquet. Aenean a sapien fermentum, congue tortor quis, volutpat nibh. Sed lacus lorem, egestas feugiat augue venenatis, pellentesque tempor leo. Suspendisse dignissim justo sem, non ullamcorper libero tincidunt vitae. Morbi ut malesuada purus, id gravida ex. Suspendisse sed pulvinar tellus. Integer hendrerit mi lacinia, rutrum velit vel, elementum orci. Aliquam lectus velit, interdum eu lorem ut, venenatis efficitur ligula.\n\nPraesent eu efficitur mauris. Morbi et gravida orci, a venenatis neque. Sed iaculis ultrices porttitor. Mauris sit amet volutpat purus, ac efficitur leo. Sed fringilla velit eget vestibulum dapibus. Mauris at efficitur nulla, nec tempor augue. Duis aliquet egestas ornare. Fusce ut pharetra sem. Sed at ante tincidunt, auctor mauris eget, vestibulum dolor. Nam sed metus eget nisi luctus efficitur. Phasellus blandit arcu id lectus auctor, in placerat orci semper. Integer sed lorem in eros luctus vulputate ac ut turpis. Pellentesque ante dui, malesuada eget placerat nec, suscipit ut nulla. Suspendisse quis laoreet ex. Vivamus pretium vitae nisi sed ultricies.\n\nAenean id neque feugiat, dictum velit quis, euismod turpis. Vivamus et tristique ligula. Integer ut risus at ipsum dignissim elementum. Morbi eu est lorem. Integer ligula est, fermentum vulputate velit in, laoreet porta purus. Nam iaculis felis id auctor ornare. Sed aliquam odio in consectetur tempor. Donec a ligula dui.\n\nSed hendrerit arcu vitae sem vestibulum, eu posuere nunc cursus. Duis ac lectus neque. Nunc ac purus ut arcu mollis fringilla eget at mi. Quisque blandit elit at est lobortis, non venenatis velit gravida. Praesent quam magna, pulvinar quis tincidunt ut, tincidunt quis quam. Donec augue enim, pellentesque ut purus et, pretium scelerisque tortor. Donec eu erat ultrices, mattis justo in, scelerisque sem. Suspendisse quis dolor mauris."
